# =============================================================================
# VPS Bootstrap - Terraform Configuration
# =============================================================================
# Bootstraps a hardened Debian 12 VPS with:
#   - WireGuard VPN (only public-facing service after hardening)
#   - Docker with isolated networking
#   - Traefik reverse proxy with Let's Encrypt via Hetzner DNS
#   - Optional services: Gitea, n8n, whoami, gogcli
#
# Usage:
#   terraform init
#   terraform apply
# =============================================================================

terraform {
  required_version = ">= 1.0"

  required_providers {
    null = {
      source  = "hashicorp/null"
      version = ">= 3.0"
    }
    random = {
      source  = "hashicorp/random"
      version = ">= 3.0"
    }
  }
}

# =============================================================================
# Random Secrets Generation
# =============================================================================

resource "random_password" "gitea_db" {
  count   = var.enable_gitea ? 1 : 0
  length  = 32
  special = false
}

resource "random_password" "gitea_secret" {
  count   = var.enable_gitea ? 1 : 0
  length  = 64
  special = false
}

resource "random_password" "n8n_db" {
  count   = var.enable_n8n ? 1 : 0
  length  = 32
  special = false
}

resource "random_password" "n8n_encryption" {
  count   = var.enable_n8n ? 1 : 0
  length  = 32
  special = false
}

# =============================================================================
# Bootstrap Environment File
# =============================================================================

locals {
  env_content = <<-EOT
# Bootstrap Environment
# Generated by Terraform - DO NOT EDIT MANUALLY

# ── Domain & DNS ─────────────────────────────────────────────────────────────
VPN_DOMAIN="${var.domain}"
VPN_HOSTNAME="${var.hostname}"
HETZNER_API_TOKEN="${var.hetzner_dns_token}"
ACME_EMAIL="${var.acme_email}"

# ── Admin User ───────────────────────────────────────────────────────────────
ADMIN_USER="${var.admin_user}"

# ── Service Flags ────────────────────────────────────────────────────────────
ENABLE_GITEA="${var.enable_gitea}"
ENABLE_N8N="${var.enable_n8n}"
ENABLE_WHOAMI="${var.enable_whoami}"ENABLE_GOGCLI="${var.enable_gogcli}"
# ── Service Secrets ──────────────────────────────────────────────────────────
%{if var.enable_gitea~}
GITEA_DB_PASSWORD="${random_password.gitea_db[0].result}"
GITEA_SECRET_KEY="${random_password.gitea_secret[0].result}"
%{endif~}
%{if var.enable_n8n~}
N8N_DB_PASSWORD="${random_password.n8n_db[0].result}"
N8N_ENCRYPTION_KEY="${random_password.n8n_encryption[0].result}"
%{endif~}

# ── VPN Clients ──────────────────────────────────────────────────────────────
VPN_CLIENTS="${join(",", var.vpn_clients)}"
EOT

  bootstrap_command = var.skip_harden ? "sudo bash ${var.repo_path}/bootstrap/apply.sh --skip-harden" : "sudo bash ${var.repo_path}/bootstrap/apply.sh"
  
  ssh_private_key = var.ssh_private_key != "" ? var.ssh_private_key : file(var.ssh_private_key_path)
}

# =============================================================================
# Clone Repository
# =============================================================================

resource "null_resource" "clone_repo" {
  triggers = {
    git_ref = var.git_ref
  }

  connection {
    type        = "ssh"
    host        = var.ssh_host
    user        = var.ssh_user
    port        = var.ssh_port
    private_key = local.ssh_private_key
  }

  provisioner "remote-exec" {
    inline = [
      "set -e",
      "apt-get update -qq && apt-get install -y -qq git",
      "rm -rf ${var.repo_path}",
      "git clone --branch ${var.git_ref} ${var.git_repo_url} ${var.repo_path}",
    ]
  }
}

# =============================================================================
# Deploy Environment File
# =============================================================================

resource "null_resource" "deploy_env" {
  depends_on = [null_resource.clone_repo]

  triggers = {
    env_hash = sha256(local.env_content)
  }

  connection {
    type        = "ssh"
    host        = var.ssh_host
    user        = var.ssh_user
    port        = var.ssh_port
    private_key = local.ssh_private_key
  }

  provisioner "file" {
    content     = local.env_content
    destination = "${var.repo_path}/bootstrap/.env"
  }

  provisioner "remote-exec" {
    inline = [
      "chmod 600 ${var.repo_path}/bootstrap/.env",
    ]
  }
}

# =============================================================================
# Run Bootstrap
# =============================================================================

resource "null_resource" "bootstrap" {
  depends_on = [null_resource.deploy_env]

  triggers = {
    env_hash   = sha256(local.env_content)
    always_run = var.force_rerun ? timestamp() : "stable"
  }

  connection {
    type        = "ssh"
    host        = var.ssh_host
    user        = var.ssh_user
    port        = var.ssh_port
    private_key = local.ssh_private_key
  }

  provisioner "remote-exec" {
    inline = [
      "set -e",
      local.bootstrap_command,
    ]
  }
}

# =============================================================================
# VPN Client Sync
# =============================================================================

resource "null_resource" "vpn_clients" {
  depends_on = [null_resource.bootstrap]

  triggers = {
    clients = join(",", var.vpn_clients)
  }

  connection {
    type        = "ssh"
    host        = var.ssh_host
    user        = var.ssh_user
    port        = var.ssh_port
    private_key = local.ssh_private_key
  }

  provisioner "remote-exec" {
    inline = [
      "${var.repo_path}/bootstrap/scripts/vpn-client.sh sync '${join(",", var.vpn_clients)}'",
    ]
  }
}
