# =============================================================================
# VPS Bootstrap - Terraform Configuration
# =============================================================================
# Bootstraps a hardened Debian 12 VPS with:
#   - WireGuard VPN (only public-facing service after hardening)
#   - Docker with isolated networking
#   - Traefik reverse proxy with Let's Encrypt via Hetzner DNS
#   - Optional services: Gitea, n8n, whoami, gogcli
#
# Usage:
#   terraform init
#   terraform apply
# =============================================================================

terraform {
  required_version = ">= 1.0"

  required_providers {
    null = {
      source  = "hashicorp/null"
      version = "~> 3.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.0"
    }
  }
}

# =============================================================================
# Random Secrets Generation
# =============================================================================

resource "random_password" "gitea_db" {
  count   = var.enable_gitea ? 1 : 0
  length  = 32
  special = false
}

resource "random_password" "gitea_secret" {
  count   = var.enable_gitea ? 1 : 0
  length  = 64
  special = false
}

resource "random_password" "gitea_internal_token" {
  count   = var.enable_gitea ? 1 : 0
  length  = 64
  special = false
}

resource "random_password" "gitea_admin_password" {
  count   = var.enable_gitea && var.gitea_admin_password == "" ? 1 : 0
  length  = 24
  special = false
}

resource "random_password" "n8n_db" {
  count   = var.enable_n8n ? 1 : 0
  length  = 32
  special = false
}

resource "random_password" "n8n_encryption" {
  count   = var.enable_n8n ? 1 : 0
  length  = 32
  special = false
}

resource "random_password" "n8n_admin_password" {
  count   = var.enable_n8n && var.n8n_admin_password == "" ? 1 : 0
  length  = 24
  special = true
}

resource "random_password" "mkdocs_webhook_secret" {
  count   = var.enable_mkdocs && var.mkdocs_webhook_secret == "" ? 1 : 0
  length  = 32
  special = false
}

# =============================================================================
# Bootstrap Environment File
# =============================================================================

locals {
  # VPN network configuration
  vpn_server_ip = "10.100.0.1"

  env_content = <<-EOT
# Bootstrap Environment
# Generated by Terraform - DO NOT EDIT MANUALLY

# ── Domain & DNS ─────────────────────────────────────────────────────────────
VPN_DOMAIN="${var.domain}"
VPN_HOSTNAME="${var.hostname}"
HETZNER_API_TOKEN="${var.hetzner_dns_token}"
ACME_EMAIL="${var.acme_email}"
LETSENCRYPT_ENABLED="${var.letsencrypt_enabled}"
LETSENCRYPT_STAGING="${var.letsencrypt_staging}"
LETSENCRYPT_REQUIRE_WHOAMI_CHECK="${var.letsencrypt_require_whoami_check}"
LETSENCRYPT_RENEW_BEFORE_DAYS="${var.letsencrypt_renew_before_days}"

# ── Admin User ───────────────────────────────────────────────────────────────
ADMIN_USER="${var.admin_user}"

# ── Service Flags ────────────────────────────────────────────────────────────
ENABLE_GITEA="${var.enable_gitea}"
ENABLE_N8N="${var.enable_n8n}"
ENABLE_WHOAMI="${var.enable_whoami}"
ENABLE_GOGCLI="${var.enable_gogcli}"
ENABLE_MKDOCS="${var.enable_mkdocs}"

# ── Service Secrets ──────────────────────────────────────────────────────────
%{if var.enable_gitea~}
GITEA_DB_PASSWORD="${random_password.gitea_db[0].result}"
GITEA_SECRET_KEY="${random_password.gitea_secret[0].result}"
GITEA_INTERNAL_TOKEN="${random_password.gitea_internal_token[0].result}"
GITEA_ADMIN_USER="${var.gitea_admin_user}"
GITEA_ADMIN_EMAIL="${var.gitea_admin_email}"
GITEA_ADMIN_PASSWORD="${var.gitea_admin_password != "" ? var.gitea_admin_password : random_password.gitea_admin_password[0].result}"
%{endif~}
%{if var.enable_n8n~}
N8N_DB_PASSWORD="${random_password.n8n_db[0].result}"
N8N_ENCRYPTION_KEY="${random_password.n8n_encryption[0].result}"
N8N_ADMIN_EMAIL="${var.n8n_admin_email}"
N8N_ADMIN_PASSWORD="${var.n8n_admin_password != "" ? var.n8n_admin_password : random_password.n8n_admin_password[0].result}"
OPENAI_API_KEY="${var.n8n_openai_api_key}"
%{endif~}
%{if var.enable_gogcli~}
GOOGLE_CLIENT_ID="${var.google_client_id}"
GOOGLE_CLIENT_SECRET="${var.google_client_secret}"
GOOGLE_PROJECT_ID="${var.google_project_id}"
%{endif~}
%{if var.enable_mkdocs~}
MKDOCS_WEBHOOK_SECRET="${var.mkdocs_webhook_secret != "" ? var.mkdocs_webhook_secret : random_password.mkdocs_webhook_secret[0].result}"
%{endif~}

# ── VPN Clients ──────────────────────────────────────────────────────────────
VPN_CLIENTS="${join(",", var.vpn_clients)}"
EOT

  # Always skip hardening in apply.sh - Terraform runs it after VPN clients exist
  bootstrap_command = "sudo bash ${var.repo_path}/bootstrap/apply.sh --skip-harden"

  # Use SSH-Agent when no explicit key is provided
  use_ssh_agent   = var.ssh_private_key == "" && var.ssh_private_key_path == ""
  ssh_private_key = local.use_ssh_agent ? null : (var.ssh_private_key != "" ? var.ssh_private_key : file(var.ssh_private_key_path))

  # Connection settings: VPN after hardening, public IP for initial setup
  effective_ssh_host = var.use_vpn ? local.vpn_server_ip : var.ssh_host
  effective_ssh_user = var.use_vpn ? var.admin_user : var.ssh_user
}

# =============================================================================
# Clone Repository
# =============================================================================

resource "null_resource" "clone_repo" {
  triggers = {
    always_run = timestamp()
  }

  connection {
    type        = "ssh"
    host        = local.effective_ssh_host
    user        = local.effective_ssh_user
    port        = var.ssh_port
    agent       = local.use_ssh_agent
    private_key = local.ssh_private_key
  }

  provisioner "remote-exec" {
    inline = [
      "set -e",
      "sudo apt-get update -qq && sudo apt-get install -y -qq git",
      "if [ -d ${var.repo_path}/.git ]; then sudo git -C ${var.repo_path} fetch origin && sudo git -C ${var.repo_path} reset --hard origin/${var.git_ref}; else sudo rm -rf ${var.repo_path} && sudo git clone --branch ${var.git_ref} ${var.git_repo_url} ${var.repo_path}; fi",
    ]
  }
}

# =============================================================================
# Deploy Environment File
# =============================================================================

resource "null_resource" "deploy_env" {
  depends_on = [null_resource.clone_repo]

  triggers = {
    env_hash = sha256(local.env_content)
    clone_id = null_resource.clone_repo.id # Re-deploy when repo is re-cloned
  }

  connection {
    type        = "ssh"
    host        = local.effective_ssh_host
    user        = local.effective_ssh_user
    port        = var.ssh_port
    agent       = local.use_ssh_agent
    private_key = local.ssh_private_key
  }

  provisioner "file" {
    content     = local.env_content
    destination = "/tmp/bootstrap.env"
  }

  provisioner "remote-exec" {
    inline = [
      "sudo mv /tmp/bootstrap.env ${var.repo_path}/bootstrap/.env",
      "sudo chmod 600 ${var.repo_path}/bootstrap/.env",
    ]
  }
}

# =============================================================================
# Run Bootstrap
# =============================================================================

resource "null_resource" "bootstrap" {
  depends_on = [null_resource.deploy_env]

  triggers = {
    env_hash   = sha256(local.env_content)
    clone_id   = null_resource.clone_repo.id
    always_run = var.force_rerun ? timestamp() : "stable"
  }

  connection {
    type        = "ssh"
    host        = local.effective_ssh_host
    user        = local.effective_ssh_user
    port        = var.ssh_port
    agent       = local.use_ssh_agent
    private_key = local.ssh_private_key
  }

  provisioner "remote-exec" {
    inline = [
      "set -e",
      local.bootstrap_command,
    ]
  }
}

# =============================================================================
# VPN Client Sync
# =============================================================================

resource "null_resource" "vpn_clients" {
  depends_on = [null_resource.bootstrap]

  triggers = {
    clients = join(",", var.vpn_clients)
  }

  connection {
    type        = "ssh"
    host        = local.effective_ssh_host
    user        = local.effective_ssh_user
    port        = var.ssh_port
    agent       = local.use_ssh_agent
    private_key = local.ssh_private_key
  }

  provisioner "remote-exec" {
    inline = [
      "sudo ${var.repo_path}/bootstrap/scripts/vpn-client.sh sync '${join(",", var.vpn_clients)}'",
    ]
  }
}

# =============================================================================
# Hardening (runs AFTER VPN clients exist)
# =============================================================================

resource "null_resource" "hardening" {
  count      = var.skip_harden ? 0 : 1
  depends_on = [null_resource.vpn_clients]

  triggers = {
    # Only run once per deployment, or when vpn_clients change
    clients = join(",", var.vpn_clients)
  }

  connection {
    type        = "ssh"
    host        = local.effective_ssh_host
    user        = local.effective_ssh_user
    port        = var.ssh_port
    agent       = local.use_ssh_agent
    private_key = local.ssh_private_key
  }

  provisioner "remote-exec" {
    inline = [
      "set -e",
      "echo ''",
      "echo '════════════════════════════════════════════════════════════════'",
      "echo '  PHASE 3: Hardening (VPN clients exist)'",
      "echo '════════════════════════════════════════════════════════════════'",
      "sudo bash ${var.repo_path}/bootstrap/core/06-harden.sh",
      "echo ''",
      "echo '╔══════════════════════════════════════════════════════════════╗'",
      "echo '║           Hardening Complete ✓                              ║'",
      "echo '╚══════════════════════════════════════════════════════════════╝'",
      "echo ''",
      "echo 'VPN Client Configs:'",
      "for client in ${join(" ", var.vpn_clients)}; do echo \"  - $client: sudo ${var.repo_path}/bootstrap/scripts/vpn-client.sh show $client\"; done",
      "echo ''",
      "echo 'After connecting VPN:'",
      "echo '  SSH:  ssh ${var.admin_user}@${local.vpn_server_ip}'",
      "echo '  Root: sudo -i'",
      "echo ''",
      "echo '════════════════════════════════════════════════════════════════'",
      "echo 'First client config (${var.vpn_clients[0]}):'",
      "echo '════════════════════════════════════════════════════════════════'",
      "sudo ${var.repo_path}/bootstrap/scripts/vpn-client.sh show '${var.vpn_clients[0]}'",
      "echo ''",
      "echo '════════════════════════════════════════════════════════════════'",
      "echo 'QR Code (scan with WireGuard app):'",
      "echo '════════════════════════════════════════════════════════════════'",
      "sudo ${var.repo_path}/bootstrap/scripts/vpn-client.sh qr '${var.vpn_clients[0]}'",
    ]
  }
}
