#!/usr/bin/env bash
# =============================================================================
# core/01-system.sh — Base system packages, sysctl, SSH hardening
# =============================================================================
# Installs required packages, configures kernel parameters, and locks down SSH
# to listen only on the WireGuard interface.
#
# Security rationale:
#   - SSH on VPN only: prevents brute-force from public internet
#   - IPv6 disabled: reduces attack surface (not needed for this deployment)
#   - Strict sysctl: prevents ICMP redirects, source routing, martian packets
#   - Conntrack tuning: supports Docker + nftables connection tracking
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "${SCRIPT_DIR}/lib/logging.sh"
source "${SCRIPT_DIR}/lib/backup.sh"

BOOTSTRAP_MODULE="system"

# Keep apt non-interactive to avoid blocking debconf/whiptail prompts
export DEBIAN_FRONTEND="${DEBIAN_FRONTEND:-noninteractive}"
APT_OPTS=(
  -o Dpkg::Options::=--force-confdef
  -o Dpkg::Options::=--force-confold
)

# ── Required packages ───────────────────────────────────────────────────────
# NOTE: systemd-resolved is NOT in this list - Debian 12 minimal uses /etc/resolv.conf
# We configure DNS directly via resolv.conf and dnsmasq for VPN
REQUIRED_PACKAGES=(
  wireguard
  wireguard-tools
  nftables
  dnsmasq
  fail2ban
  curl
  ca-certificates
  gnupg
  lsb-release
  git
  jq
  unattended-upgrades
  apt-transport-https
  iproute2
)

# ── Prepare DNS resolution ──────────────────────────────────────────────────
# Hetzner images may have dnsmasq pre-installed. Stop it before installation.
# We use /etc/resolv.conf directly (not systemd-resolved - not on all images).
prepare_dns_resolution() {
  log_step "Preparing DNS resolution"

  # Check if dnsmasq is running and blocking DNS
  if systemctl is-active --quiet dnsmasq 2>/dev/null; then
    log_info "Stopping pre-installed dnsmasq (will configure for VPN later)"
    systemctl stop dnsmasq || true
    # Don't disable yet - we'll configure it properly for VPN later
  fi

  # Ensure /etc/resolv.conf has working nameservers
  if ! grep -q 'nameserver' /etc/resolv.conf 2>/dev/null; then
    log_info "Setting DNS in /etc/resolv.conf"
    echo "nameserver 1.1.1.1" > /etc/resolv.conf
    echo "nameserver 8.8.8.8" >> /etc/resolv.conf
  fi

  # Verify DNS actually works
  if ! host -W 2 deb.debian.org 1.1.1.1 >/dev/null 2>&1; then
    log_warn "DNS via 1.1.1.1 failed; configuring fallback"
    cp /etc/resolv.conf /etc/resolv.conf.backup 2>/dev/null || true
    echo "nameserver 1.1.1.1" > /etc/resolv.conf
    echo "nameserver 8.8.8.8" >> /etc/resolv.conf
  fi

  log_info "DNS resolution ready"
}

install_packages() {
  log_step "Installing required packages"

  # Check which packages are already installed
  local to_install=()
  for pkg in "${REQUIRED_PACKAGES[@]}"; do
    if dpkg-query -W -f='${Status}' "$pkg" 2>/dev/null | grep -q 'install ok installed'; then
      log_debug "Already installed: $pkg"
    else
      to_install+=("$pkg")
    fi
  done

  if [[ ${#to_install[@]} -eq 0 ]]; then
    log_info "All required packages already installed"
    return 0
  fi

  log_info "Installing ${#to_install[@]} package(s): ${to_install[*]}"
  run_cmd env DEBIAN_FRONTEND="$DEBIAN_FRONTEND" apt-get update -qq
  run_cmd env DEBIAN_FRONTEND="$DEBIAN_FRONTEND" apt-get install "${APT_OPTS[@]}" -y -qq ${to_install[*]}

  # CRITICAL: Stop dnsmasq immediately after install - it auto-starts and blocks port 53
  # This breaks systemd-resolved which we need for apt operations.
  # dnsmasq will be configured properly later to listen only on wg0.
  if systemctl is-active --quiet dnsmasq 2>/dev/null; then
    log_info "Stopping dnsmasq (auto-started by apt, conflicts with systemd-resolved)"
    systemctl stop dnsmasq || true
    systemctl disable dnsmasq || true
  fi

  # Ensure DNS is working via /etc/resolv.conf (systemd-resolved not available)
  if ! grep -q 'nameserver' /etc/resolv.conf 2>/dev/null; then
    echo 'nameserver 1.1.1.1' > /etc/resolv.conf
    echo 'nameserver 8.8.8.8' >> /etc/resolv.conf
  fi
  log_info "DNS configured via /etc/resolv.conf"
  sleep 1
}

# ── Sysctl hardening ────────────────────────────────────────────────────────
configure_sysctl() {
  log_step "Configuring sysctl parameters"

  local sysctl_file="/etc/sysctl.d/99-bootstrap-hardening.conf"

  local content
  content="$(cat <<'SYSCTL'
# =============================================================================
# 99-bootstrap-hardening.conf — Kernel parameters for VPS hardening
# =============================================================================
# Generated by bootstrap system. Do not edit manually.

# ── IPv4 forwarding ─────────────────────────────────────────────────────────
# Required for WireGuard → Docker network routing
net.ipv4.ip_forward = 1
net.ipv4.conf.all.forwarding = 1

# ── IPv6 disabled ────────────────────────────────────────────────────────────
# Not used in this deployment; reduces attack surface
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
# Keep IPv6 on eth0 for Hetzner compatibility (link-local needed for gateway)
net.ipv6.conf.eth0.disable_ipv6 = 0
# Disable DAD — not needed when IPv6 is mostly off
net.ipv6.conf.all.accept_dad = 0

# ── Anti-spoofing / hardening ────────────────────────────────────────────────
# Loose reverse path filter (strict=1 breaks asymmetric Docker routing)
net.ipv4.conf.all.rp_filter = 2
# Log packets with impossible addresses
net.ipv4.conf.all.log_martians = 1
# Reject ICMP redirects (prevent MITM via gateway spoofing)
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.all.send_redirects = 0
# Reject source-routed packets (prevent routing manipulation)
net.ipv4.conf.all.accept_source_route = 0

# ── Connection tracking ─────────────────────────────────────────────────────
# Higher limit for Docker + nftables conntrack table
net.netfilter.nf_conntrack_max = 262144

# ── Socket backlog ──────────────────────────────────────────────────────────
net.core.somaxconn = 4096
SYSCTL
)"

  if file_matches "$sysctl_file" "$content"; then
    log_info "Sysctl config already up to date"
    return 0
  fi

  install_content "$content" "$sysctl_file" "0644"

  if [[ "$DRY_RUN" != "true" ]]; then
    sysctl --system >/dev/null 2>&1
    log_info "Sysctl parameters applied"
  fi
}

# ── SSH hardening ────────────────────────────────────────────────────────────
# IMPORTANT: We do NOT restrict SSH to wg0 during initial bootstrap!
# Reason: If wg0 fails to come up, you lose all access to the server.
#
# Strategy:
#   1. Initial bootstrap: SSH listens on ALL interfaces (0.0.0.0)
#   2. After VPN is verified working: run core/06-harden.sh (via Terraform or manual)
#   3. 06-harden.sh restricts SSH to VPN only and enables fail2ban
configure_ssh() {
  log_step "Configuring SSH (hardening, but NOT restricting to VPN yet)"

  local sshd_conf="/etc/ssh/sshd_config.d/99-bootstrap.conf"

  # SAFETY: Keep SSH accessible on all interfaces during bootstrap
  # The firewall (nftables) will still block SSH from WAN after core/03-firewall
  # but SSH will work via console/recovery if wg0 fails
  local content
  content="$(cat <<'SSHD'
# =============================================================================
# 99-bootstrap.conf — SSH hardening
# =============================================================================
# SSH listens on ALL interfaces during initial bootstrap.
# After VPN is verified, 06-harden.sh restricts SSH to wg0 only.
#
# SECURITY: nftables blocks SSH from WAN (eth0), so this is safe.
#           SSH is only reachable via VPN (wg0) or console.

# Listen on all interfaces (firewall blocks WAN access)
ListenAddress 0.0.0.0

# Disable password auth — keys only
PasswordAuthentication no
PermitRootLogin prohibit-password

# Disable unused auth methods
KbdInteractiveAuthentication no
ChallengeResponseAuthentication no
UsePAM yes

# Limit sessions
MaxAuthTries 3
MaxSessions 3
LoginGraceTime 30

# Disable forwarding unless needed
AllowTcpForwarding no
X11Forwarding no
SSHD
)"

  if file_matches "$sshd_conf" "$content"; then
    log_info "SSH config already up to date"
    return 0
  fi

  install_content "$content" "$sshd_conf" "0644"

  # Validate SSH config before restarting
  if [[ "$DRY_RUN" != "true" ]]; then
    if sshd -t 2>/dev/null; then
      log_info "SSH config validation passed"
      if systemctl is-active --quiet ssh.service; then
        systemctl reload ssh.service
        log_info "SSH service reloaded"
      fi
    else
      log_error "SSH config validation FAILED — reverting"
      rm -f "$sshd_conf"
      log_fatal "SSH config was invalid, removed $sshd_conf"
    fi
  fi
}

# ── Disable cloud-init ───────────────────────────────────────────────────────
# Cloud-init can override our configs on reboot. Disable it.
disable_cloud_init() {
  log_step "Disabling cloud-init"

  if [[ "$DRY_RUN" == "true" ]]; then
    log_info "Would disable cloud-init"
    return 0
  fi

  # Method 1: Create disable file
  touch /etc/cloud/cloud-init.disabled 2>/dev/null || true

  # Method 2: Disable services
  local ci_services=(
    cloud-init-local.service
    cloud-init.service
    cloud-config.service
    cloud-final.service
  )
  
  for svc in "${ci_services[@]}"; do
    if systemctl is-enabled --quiet "$svc" 2>/dev/null; then
      systemctl disable "$svc" 2>/dev/null || true
      systemctl stop "$svc" 2>/dev/null || true
      log_debug "Disabled $svc"
    fi
  done

  # Method 3: Mask to prevent re-enabling
  systemctl mask cloud-init.service 2>/dev/null || true

  # Prevent cloud-init from managing network
  if [[ -d /etc/cloud/cloud.cfg.d ]]; then
    cat > /etc/cloud/cloud.cfg.d/99-disable-network.cfg << 'CLOUDINIT'
# Disable cloud-init network configuration
network: {config: disabled}
CLOUDINIT
  fi

  log_info "cloud-init disabled"
}

# ── Hostname ─────────────────────────────────────────────────────────────────
configure_hostname() {
  log_step "Setting hostname"

  # Use VPN_DOMAIN prefix or 'vps' as hostname
  local desired="${VPN_HOSTNAME:-vps}"
  local current
  current="$(hostname)"

  if [[ "$current" == "$desired" ]]; then
    log_info "Hostname already set to $desired"
    return 0
  fi

  run_cmd hostnamectl set-hostname "$desired"
  log_info "Hostname set to $desired"
}

# ── Unattended upgrades ─────────────────────────────────────────────────────
configure_unattended_upgrades() {
  log_step "Enabling unattended security upgrades"

  if systemctl is-enabled --quiet unattended-upgrades.service 2>/dev/null; then
    log_info "unattended-upgrades already enabled"
    return 0
  fi

  run_cmd systemctl enable --now unattended-upgrades.service
}

# ── Docker interface sysctl (applied after Docker creates bridges) ───────────
configure_docker_bridge_sysctl() {
  log_step "Creating systemd service for Docker bridge sysctl"

  # Docker bridge interfaces need special sysctl after they're created.
  # rp_filter=0 and route_localnet=1 are required for br-vpn to work
  # with nftables (since Docker iptables is disabled).
  local unit_file="/etc/systemd/system/b3rn-sysctl-ifaces.service"

  local content
  content="$(cat <<'UNIT'
[Unit]
Description=Apply per-interface sysctl for Docker bridges
After=docker.service
Wants=docker.service

[Service]
Type=oneshot
RemainAfterExit=yes
# Wait for Docker to create bridge interfaces
ExecStartPre=/bin/sleep 5
# br-vpn: Docker service network — needs relaxed rp_filter for nftables routing
ExecStart=/sbin/sysctl -w net.ipv4.conf.br-vpn.rp_filter=0
ExecStart=/sbin/sysctl -w net.ipv4.conf.br-vpn.route_localnet=1
# wg0: WireGuard — asymmetric routing requires relaxed rp_filter
ExecStart=/sbin/sysctl -w net.ipv4.conf.wg0.rp_filter=0
# docker0: default bridge — same relaxation for consistency
ExecStart=/sbin/sysctl -w net.ipv4.conf.docker0.rp_filter=0
ExecStart=/sbin/sysctl -w net.ipv4.conf.docker0.route_localnet=1

[Install]
WantedBy=multi-user.target
UNIT
)"

  if file_matches "$unit_file" "$content"; then
    log_info "b3rn-sysctl-ifaces.service already up to date"
    return 0
  fi

  install_content "$content" "$unit_file" "0644"

  if [[ "$DRY_RUN" != "true" ]]; then
    systemctl daemon-reload
    systemctl enable b3rn-sysctl-ifaces.service
    log_info "b3rn-sysctl-ifaces.service enabled"
  fi
}

# ── Create admin user ────────────────────────────────────────────────────────
# Creates admin user with sudo access and copies SSH keys from root
create_admin_user() {
  log_step "Creating admin user"

  local admin_user="${ADMIN_USER:-admin}"

  # Create user if not exists
  if id "$admin_user" &>/dev/null; then
    log_info "Admin user '$admin_user' already exists"
  else
    useradd -m -s /bin/bash "$admin_user"
    log_info "Created admin user: $admin_user"
  fi

  # Add to sudo group
  usermod -aG sudo "$admin_user"

  # Configure passwordless sudo
  echo "$admin_user ALL=(ALL) NOPASSWD:ALL" > "/etc/sudoers.d/99-$admin_user"
  chmod 440 "/etc/sudoers.d/99-$admin_user"
  log_info "Configured passwordless sudo for $admin_user"

  # Copy SSH keys from root
  local admin_home
  admin_home="$(getent passwd "$admin_user" | cut -d: -f6)"
  local admin_ssh="${admin_home}/.ssh"

  if [[ -f /root/.ssh/authorized_keys ]]; then
    mkdir -p "$admin_ssh"
    cp /root/.ssh/authorized_keys "$admin_ssh/authorized_keys"
    chown -R "$admin_user:$admin_user" "$admin_ssh"
    chmod 700 "$admin_ssh"
    chmod 600 "$admin_ssh/authorized_keys"
    log_info "Copied SSH keys from root to $admin_user"
  else
    log_warn "No SSH keys found for root - admin user will have no SSH access"
  fi
}

# ── Main ─────────────────────────────────────────────────────────────────────
main() {
  module_start "$BOOTSTRAP_MODULE"
  require_root

  prepare_dns_resolution    # IMPORTANT: Fix DNS before apt runs
  install_packages
  disable_cloud_init        # IMPORTANT: Prevent cloud-init from overwriting our configs
  configure_hostname
  configure_sysctl
  configure_ssh
  create_admin_user         # Create admin user with SSH keys
  configure_docker_bridge_sysctl
  configure_unattended_upgrades

  module_done
}

# Allow sourcing without execution
if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
  main "$@"
fi
