#!/usr/bin/env bash
# =============================================================================
# core/03-firewall.sh — nftables ruleset
# =============================================================================
# Implements the complete packet filter for the VPS.
#
# ┌─────────────────────────────────────────────────────────────────────────┐
# │ TRAFFIC FLOW DIAGRAM                                                    │
# │                                                                         │
# │ Internet ──UDP/51820──► eth0 ──► wg0 (10.100.0.0/24)                   │
# │                                   │                                     │
# │                                   ├──SSH──► 10.100.0.1:22 (host)       │
# │                                   ├──DNS──► 10.100.0.1:53 (dnsmasq)   │
# │                                   │                                     │
# │                                   └──HTTP/S──► br-vpn (10.20.0.0/24)  │
# │                                                  │                      │
# │                                        ONLY to Traefik (10.20.0.10)    │
# │                                        ports 80, 443, 2222             │
# │                                                  │                      │
# │                                        Traefik ──► whoami (10.20.0.20) │
# │                                                ──► gitea  (10.20.0.30) │
# │                                                ──► pg     (10.20.0.31) │
# └─────────────────────────────────────────────────────────────────────────┘
#
# Security rationale — each rule is annotated below.
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "${SCRIPT_DIR}/lib/logging.sh"
source "${SCRIPT_DIR}/lib/backup.sh"

BOOTSTRAP_MODULE="firewall"

# ── Generate nftables ruleset ────────────────────────────────────────────────
# CRITICAL: This ruleset allows SSH on WAN during bootstrap phase.
# After VPN is verified working, 06-harden.sh restricts SSH to VPN only.
generate_ruleset() {
  cat <<'NFT'
#!/usr/sbin/nft -f
# =============================================================================
# nftables.conf — VPS Packet Filter
# =============================================================================
# Generated by bootstrap system. Do not edit manually.
# Re-run bootstrap to update.
#
# Design principles:
#   1. Default DROP on input and forward
#   2. Only UDP/51820 (WireGuard) and TCP/22 (SSH) from WAN
#   3. VPN clients reach services ONLY through Traefik
#   4. Docker iptables disabled — all filtering via nftables
#
# ⚠️  BOOTSTRAP MODE: SSH is allowed on WAN for recovery.
#    After VPN is working, 06-harden.sh disables WAN SSH.
# =============================================================================

flush ruleset

# ── Variables ────────────────────────────────────────────────────────────────
define WAN_IF     = "eth0"
define VPN_IF     = "wg0"
define DKR_IF     = "br-vpn"

define VPN_NET    = 10.100.0.0/24
define DKR_NET    = 10.20.0.0/24
define TRAEFIK_IP = 10.20.0.10
define PIHOLE_IP  = 10.20.0.71

# =============================================================================
# inet filter — Layer 3/4 packet filtering (IPv4 + IPv6)
# =============================================================================
table inet filter {

  # ── INPUT chain ────────────────────────────────────────────────────────────
  # Controls traffic destined for the host itself.
  chain input {
    type filter hook input priority filter; policy drop;

    # Drop invalid connection tracking states (malformed/out-of-state packets)
    ct state invalid drop

    # Allow established and related connections (return traffic)
    ct state established,related accept

    # Allow all loopback traffic (required for systemd-resolved, local services)
    iif "lo" accept

    # Allow ICMP (ping) — useful for diagnostics, low risk
    ip protocol icmp accept

    # Drop ALL IPv6 — not used in this deployment
    meta nfproto ipv6 drop

    # ── WAN rules ────────────────────────────────────────────────────────────
    # Allow DHCP responses from Hetzner gateway (required for eth0 IP assignment)
    iifname $WAN_IF udp sport 67 udp dport 68 accept

    # Allow WireGuard handshakes from internet
    # Rate-limited to 25/s burst 50 to mitigate UDP amplification/DoS
    iifname $WAN_IF udp dport 51820 limit rate 25/second burst 50 packets accept

    # ⚠️  BOOTSTRAP MODE: Allow SSH on WAN for recovery access
    # This rule is removed by 06-harden.sh after VPN is verified working.
    # Rate-limited to prevent brute-force attacks.
    iifname $WAN_IF tcp dport 22 limit rate 10/minute burst 5 packets accept comment "bootstrap-ssh-wan"

    # ── VPN rules ────────────────────────────────────────────────────────────
    # Allow SSH from VPN clients to host (10.100.0.1:22)
    iifname $VPN_IF ip saddr $VPN_NET tcp dport 22 accept

    # Allow DNS from VPN clients to dnsmasq (10.100.0.1:53)
    # dnsmasq resolves *.<domain> → Traefik IP (single ingress)
    iifname $VPN_IF ip saddr $VPN_NET udp dport 53 accept
    iifname $VPN_IF ip saddr $VPN_NET tcp dport 53 accept

    # ── Default: log and drop ────────────────────────────────────────────────
    # Rate-limited logging prevents log flooding from port scans
    limit rate 5/second burst 20 packets log prefix "nft input drop: " flags all counter drop
  }

  # ── FORWARD chain ─────────────────────────────────────────────────────────
  # Controls traffic routed THROUGH the host (between interfaces).
  chain forward {
    type filter hook forward priority filter; policy drop;

    # Drop invalid states
    ct state invalid drop

    # Allow return traffic for established connections
    ct state established,related accept

    # ── Docker internal: container-to-container on vpn_net ───────────────────
    # Allow containers on br-vpn to talk to each other
    # (e.g., gitea → postgres, traefik → backends)
    iifname $DKR_IF oifname $DKR_IF ip saddr $DKR_NET ip daddr $DKR_NET accept

    # ── VPN → Traefik ONLY ──────────────────────────────────────────────────
    # CRITICAL SECURITY RULE:
    # VPN clients can ONLY reach Traefik's IP on ports 80 (HTTP→HTTPS redirect),
    # 443 (HTTPS), and 2222 (Git SSH).
    # They CANNOT reach any other container directly.
    # This enforces single-ingress: all traffic flows through Traefik.
    iifname $VPN_IF oifname $DKR_IF ip saddr $VPN_NET ip daddr $TRAEFIK_IP tcp dport { 80, 443, 2222 } accept

    # ── VPN → Pi-hole DNS (optional) ────────────────────────────────────────
    # Allow VPN clients to use Pi-hole as DNS server (if deployed).
    # Pi-hole is at 10.20.0.71:53 (UDP/TCP).
    # This is harmless if Pi-hole is not running.
    iifname $VPN_IF oifname $DKR_IF ip saddr $VPN_NET ip daddr $PIHOLE_IP udp dport 53 accept
    iifname $VPN_IF oifname $DKR_IF ip saddr $VPN_NET ip daddr $PIHOLE_IP tcp dport 53 accept

    # ── Docker → Internet (outbound) ────────────────────────────────────────
    # Allow containers to reach the internet (for package updates, ACME, etc.)
    iifname $DKR_IF oifname $WAN_IF ip saddr $DKR_NET accept

    # ── VPN → Internet (outbound) ───────────────────────────────────────────
    # Allow VPN clients to route internet traffic through the VPS
    iifname $VPN_IF oifname $WAN_IF ip saddr $VPN_NET accept

    # ── Default: log and drop ────────────────────────────────────────────────
    limit rate 5/second burst 20 packets log prefix "nft forward drop: " flags all counter drop
  }

  # ── OUTPUT chain ──────────────────────────────────────────────────────────
  # No restrictions on outbound traffic from the host itself
  chain output {
    type filter hook output priority filter; policy accept;
  }
}

# =============================================================================
# ip nat — Network Address Translation
# =============================================================================
table ip nat {
  chain postrouting {
    type nat hook postrouting priority srcnat; policy accept;

    # Masquerade Docker container traffic going to internet
    # Required because Docker iptables is disabled — we handle NAT manually
    oifname $WAN_IF ip saddr $DKR_NET masquerade

    # Masquerade VPN client traffic going to internet
    oifname $WAN_IF ip saddr $VPN_NET masquerade
  }
}
NFT
}

# ── Install and validate ruleset ─────────────────────────────────────────────
install_firewall() {
  log_step "Installing nftables ruleset"

  local nft_conf="/etc/nftables.conf"
  local ruleset
  ruleset="$(generate_ruleset)"

  if file_matches "$nft_conf" "$ruleset"; then
    log_info "nftables.conf already up to date"
    return 0
  fi

  # Write to temp file and validate BEFORE applying
  local tmpfile
  tmpfile="$(mktemp /tmp/nftables.XXXXXX.conf)"
  printf '%s\n' "$ruleset" > "$tmpfile"

  if [[ "$DRY_RUN" == "true" ]]; then
    log_info "Would install nftables ruleset"
    log_info "Validating syntax..."
    if nft -c -f "$tmpfile" 2>/dev/null; then
      log_info "✅ nftables syntax check passed"
    else
      log_error "❌ nftables syntax check FAILED"
    fi
    rm -f "$tmpfile"
    return 0
  fi

  # Syntax check
  log_info "Validating nftables syntax..."
  if ! nft -c -f "$tmpfile"; then
    rm -f "$tmpfile"
    log_fatal "nftables syntax validation FAILED — not applying"
  fi
  log_info "✅ nftables syntax check passed"

  # Back up current rules
  backup_file "$nft_conf"

  # Install atomically
  chmod 0600 "$tmpfile"
  mv -f "$tmpfile" "$nft_conf"
  chown root:root "$nft_conf"
  log_info "Installed $nft_conf"

  # Apply the ruleset
  nft -f "$nft_conf"
  log_info "nftables ruleset applied"
}

# ── Enable nftables service ──────────────────────────────────────────────────
enable_nftables() {
  log_step "Enabling nftables service"

  if [[ "$DRY_RUN" == "true" ]]; then
    log_info "Would enable nftables.service"
    return 0
  fi

  systemctl enable nftables.service
  # nftables.service is a oneshot that loads /etc/nftables.conf at boot
  # We already applied the rules above, so just ensure the service is enabled
  systemctl restart nftables.service
  log_info "nftables.service enabled and restarted"
}

# ── Validate applied rules ──────────────────────────────────────────────────
validate_firewall() {
  log_step "Validating applied firewall rules"

  if [[ "$DRY_RUN" == "true" ]]; then
    log_info "Skipping firewall validation in dry-run mode"
    return 0
  fi

  # Check that input policy is drop
  local input_policy
  input_policy="$(nft list chain inet filter input 2>/dev/null | grep 'policy' | awk '{print $NF}' | tr -d ';')"
  if [[ "$input_policy" == "drop" ]]; then
    log_info "✅ Input policy: drop"
  else
    log_error "❌ Input policy: $input_policy (expected: drop)"
    return 1
  fi

  # Check that forward policy is drop
  local forward_policy
  forward_policy="$(nft list chain inet filter forward 2>/dev/null | grep 'policy' | awk '{print $NF}' | tr -d ';')"
  if [[ "$forward_policy" == "drop" ]]; then
    log_info "✅ Forward policy: drop"
  else
    log_error "❌ Forward policy: $forward_policy (expected: drop)"
    return 1
  fi

  # Verify no stale network references in active ruleset
  if nft list ruleset 2>/dev/null | grep -qE '10\.99\.0\.'; then
    log_error "❌ Found stale 10.99.0.x reference in active ruleset"
    return 1
  else
    log_info "✅ No stale network references in active ruleset"
  fi

  log_info "✅ Firewall validation passed"
}

# ── Main ─────────────────────────────────────────────────────────────────────
main() {
  module_start "$BOOTSTRAP_MODULE"
  require_root

  install_firewall
  enable_nftables
  validate_firewall

  module_done
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
  main "$@"
fi
