#!/usr/bin/env bash
# =============================================================================
# core/05-traefik.sh — Traefik reverse proxy (file provider only)
# =============================================================================
# Deploys Traefik as the SINGLE INGRESS POINT for all services.
#
# Architecture:
#   VPN Client → dnsmasq → *.<domain> → 10.20.0.10 (Traefik)
#   Traefik → host-header routing → backend containers
#
# Security design:
#   - NO Docker socket provider (prevents container escape → full host control)
#   - File provider only (static routing, no runtime service discovery)
#   - No dashboard (reduces attack surface)
#   - No published ports (container IPs only, routed by nftables)
#   - ipAllowList middleware: only VPN clients can access
#   - TLS via Let's Encrypt DNS-01 challenge (no public port 80 needed)
#   - Read-only root filesystem
#   - Dropped all capabilities except NET_BIND_SERVICE
#   - Runs as non-root user (65532)
#   - no-new-privileges security option
#
# ACME DNS-01:
#   Uses Hetzner DNS API for certificate provisioning.
#   This allows TLS certificates without exposing HTTP/HTTPS to the internet.
#   The HETZNER_API_TOKEN must have DNS zone edit permissions.
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "${SCRIPT_DIR}/lib/logging.sh"
source "${SCRIPT_DIR}/lib/backup.sh"

BOOTSTRAP_MODULE="traefik"

# Load environment
if [[ -f "${SCRIPT_DIR}/.env" ]]; then
  # shellcheck source=/dev/null
  source "${SCRIPT_DIR}/.env"
fi

HETZNER_API_TOKEN="${HETZNER_API_TOKEN:-__ACME_DNS_TOKEN__}"
ACME_EMAIL="${ACME_EMAIL:-admin@example.com}"
VPN_DOMAIN="${VPN_DOMAIN:-example.com}"

TRAEFIK_DIR="/opt/traefik"

# ── Create directory structure ───────────────────────────────────────────────
setup_directories() {
  log_step "Creating Traefik directory structure"

  if [[ "$DRY_RUN" == "true" ]]; then
    log_info "Would create $TRAEFIK_DIR"
    return 0
  fi

  mkdir -p "${TRAEFIK_DIR}/letsencrypt"
  # letsencrypt directory must be writable by traefik user (65532)
  chown -R 65532:65532 "${TRAEFIK_DIR}/letsencrypt"
  chmod 0700 "${TRAEFIK_DIR}/letsencrypt"
  log_info "Created $TRAEFIK_DIR"
}

# ── Generate traefik.yml (static config) ─────────────────────────────────────
install_traefik_config() {
  log_step "Installing Traefik static configuration"

  local config_file="${TRAEFIK_DIR}/traefik.yml"

  local content
  content="$(cat <<YAML
# =============================================================================
# traefik.yml — Traefik static configuration
# =============================================================================
# Generated by bootstrap system. Do not edit manually.

global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: INFO

# ── Entrypoints ──────────────────────────────────────────────────────────────
# websecure (443): HTTPS for web services (whoami, gitea)
# gitssh (2222): TCP passthrough for Git SSH
# NO port 80 entrypoint — all traffic is TLS
entryPoints:
  websecure:
    address: ":443"
  gitssh:
    address: ":2222"

# ── File provider ONLY ──────────────────────────────────────────────────────
# SECURITY: No Docker socket provider.
# Docker socket access = root-equivalent privilege escalation vector.
# File provider gives deterministic, auditable routing.
providers:
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

# ── ACME / Let's Encrypt ────────────────────────────────────────────────────
# DNS-01 challenge via Hetzner DNS API.
# This allows TLS certificate provisioning WITHOUT exposing any HTTP port
# to the public internet. The only public port is UDP/51820 (WireGuard).
certificatesResolvers:
  le:
    acme:
      email: ${ACME_EMAIL}
      storage: /letsencrypt/acme.json
      dnsChallenge:
        provider: hetzner
        # Wait 60s after setting TXT record before asking Let's Encrypt to validate.
        # Hetzner DNS propagation can take 30-60s — without this delay,
        # secondary validators see stale/wrong TXT records → 403 Unauthorized.
        delayBeforeCheck: 60
        resolvers:
          - "1.1.1.1:53"
          - "9.9.9.9:53"

# ── API / Dashboard ─────────────────────────────────────────────────────────
# DISABLED. Dashboard exposes internal routing information and
# is an unnecessary attack surface for a headless VPN-only deployment.
api:
  dashboard: false
  insecure: false
YAML
)"

  if file_matches "$config_file" "$content"; then
    log_info "traefik.yml already up to date"
    return 0
  fi

  install_content "$content" "$config_file" "0644"
}

# ── Generate dynamic.yml (routing rules) ─────────────────────────────────────
install_dynamic_config() {
  log_step "Installing Traefik dynamic configuration"

  local config_file="${TRAEFIK_DIR}/dynamic.yml"

  # Dynamic config defines all routes and middlewares.
  # vpn-only middleware ensures only VPN clients (10.100.0.0/24)
  # and the Docker bridge gateway (10.20.0.1) can access services.
  local content
  content="$(cat <<YAML
# =============================================================================
# dynamic.yml — Traefik dynamic routing configuration
# =============================================================================
# Generated by bootstrap system. Do not edit manually.

# ── HTTP routers & services ──────────────────────────────────────────────────
http:
  middlewares:
    # SECURITY: Only allow access from VPN subnet and Docker bridge gateway.
    # This is a defense-in-depth measure on top of nftables rules.
    # Even if nftables were misconfigured, Traefik would still reject
    # non-VPN traffic.
    vpn-only:
      ipAllowList:
        sourceRange:
          - 10.100.0.0/24
          - 10.20.0.1/32

  routers:
    # whoami: diagnostic/test service
    whoami:
      entryPoints: ["websecure"]
      rule: "Host(\`whoami.${VPN_DOMAIN}\`)"
      middlewares: ["vpn-only"]
      service: whoami-svc
      tls:
        certResolver: le

    # Gitea web UI
    git-web:
      entryPoints: ["websecure"]
      rule: "Host(\`git.${VPN_DOMAIN}\`)"
      middlewares: ["vpn-only"]
      service: git-web-svc
      tls:
        certResolver: le

  services:
    whoami-svc:
      loadBalancer:
        servers:
          - url: "http://10.20.0.20:80"

    git-web-svc:
      loadBalancer:
        servers:
          - url: "http://10.20.0.30:3000"

# ── TCP routers & services ──────────────────────────────────────────────────
tcp:
  middlewares:
    # Same VPN-only restriction for TCP (Git SSH)
    vpn-only-tcp:
      ipAllowList:
        sourceRange:
          - 10.100.0.0/24
          - 10.20.0.1/32

  routers:
    # Git SSH: TCP passthrough to Gitea SSH server
    git-ssh:
      entryPoints: ["gitssh"]
      rule: "HostSNI(\`*\`)"
      middlewares: ["vpn-only-tcp"]
      service: git-ssh-svc

  services:
    git-ssh-svc:
      loadBalancer:
        servers:
          - address: "10.20.0.30:2222"

# ── TLS: wildcard certificate ────────────────────────────────────────────────
# Request a single *.${VPN_DOMAIN} wildcard cert via DNS-01 (Hetzner).
# This covers ALL subdomains (git, whoami, 8n8, ...) with one cert.
tls:
  stores:
    default:
      defaultGeneratedCert:
        resolver: le
        domain:
          main: "*.${VPN_DOMAIN}"
          sans:
            - "${VPN_DOMAIN}"
YAML
)"

  if file_matches "$config_file" "$content"; then
    log_info "dynamic.yml already up to date"
    return 0
  fi

  install_content "$content" "$config_file" "0644"
}

# ── Generate docker-compose.yml ──────────────────────────────────────────────
install_compose_file() {
  log_step "Installing Traefik docker-compose.yml"

  local compose_file="${TRAEFIK_DIR}/docker-compose.yml"

  # SECURITY NOTES on compose config:
  # - NO "ports:" directive — container is NOT published to host network
  #   Traffic reaches Traefik via nftables forwarding to its container IP
  # - read_only: true — prevents runtime filesystem modifications
  # - cap_drop ALL + cap_add NET_BIND_SERVICE — minimum privileges
  # - user 65532: runs as nobody (non-root)
  # - no-new-privileges: prevents setuid/setgid escalation inside container
  # - tmpfs /tmp: writable temp area in read-only filesystem
  # - volumes are :ro except letsencrypt (needs write for ACME state)
  local content
  content="$(cat <<'YAML'
# =============================================================================
# docker-compose.yml — Traefik reverse proxy
# =============================================================================
# NO ports: directive — Traefik is NOT exposed to host network.
# Reachable only via Docker network IP (10.20.0.10) through nftables.

services:
  traefik:
    image: traefik:v3.6.7
    container_name: traefik
    restart: unless-stopped
    user: "65532:65532"
    security_opt:
      - no-new-privileges:true
    cap_drop: ["ALL"]
    cap_add: ["NET_BIND_SERVICE"]
    read_only: true
    tmpfs: ["/tmp"]
    environment:
      - HETZNER_API_TOKEN=${HETZNER_API_TOKEN}
      # CRITICAL: Hetzner migrated DNS API to Cloud API (2025+)
      # Without this, LEGO uses the old dns.hetzner.com endpoint which fails
      - HETZNER_API_URL=https://api.hetzner.cloud/v1
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./dynamic.yml:/etc/traefik/dynamic.yml:ro
      - ./letsencrypt:/letsencrypt
    networks:
      vpn_net:
        ipv4_address: 10.20.0.10

networks:
  vpn_net:
    external: true
YAML
)"

  if file_matches "$compose_file" "$content"; then
    log_info "docker-compose.yml already up to date"
    return 0
  fi

  install_content "$content" "$compose_file" "0644"
}

# ── Generate .env file ──────────────────────────────────────────────────────
install_env_file() {
  log_step "Installing Traefik .env file"

  local env_file="${TRAEFIK_DIR}/.env"

  if [[ "$HETZNER_API_TOKEN" == "__ACME_DNS_TOKEN__" ]]; then
    log_warn "HETZNER_API_TOKEN not set — using placeholder"
  fi

  local content="HETZNER_API_TOKEN=${HETZNER_API_TOKEN}"

  if file_matches "$env_file" "$content"; then
    log_info ".env already up to date"
    return 0
  fi

  install_content "$content" "$env_file" "0600"
}

# ── Deploy Traefik stack ─────────────────────────────────────────────────────
deploy_traefik() {
  log_step "Deploying Traefik stack"

  if [[ "$DRY_RUN" == "true" ]]; then
    log_info "Would deploy Traefik via docker compose"
    return 0
  fi

  cd "${TRAEFIK_DIR}"

  # NOTE: `docker compose pull` can deadlock under non-interactive Terraform
  # remote-exec sessions with current Compose releases. `up -d` already pulls
  # missing images, so use that directly to avoid indefinite bootstrap hangs.
  docker compose up -d --remove-orphans

  # Wait for container to be healthy
  local i=0
  while [[ $i -lt 30 ]]; do
    if docker ps --filter "name=traefik" --filter "status=running" --format '{{.Names}}' | grep -q traefik; then
      log_info "Traefik container is running"
      return 0
    fi
    sleep 1
    i=$((i + 1))
  done

  log_warn "Traefik container may not be fully started yet"
}

# ── Main ─────────────────────────────────────────────────────────────────────
main() {
  module_start "$BOOTSTRAP_MODULE"
  require_root

  setup_directories
  install_traefik_config
  install_dynamic_config
  install_compose_file
  install_env_file
  deploy_traefik

  module_done
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
  main "$@"
fi
