#!/usr/bin/env bash
# =============================================================================
# core/06-harden.sh — Final hardening (SSH VPN-only, Root lockdown)
# =============================================================================
# CRITICAL: This module runs LAST and locks down the server!
#   - SSH only listens on VPN interface (10.100.0.1)
#   - Root login disabled
#   - Only admin user with passwordless sudo
#   - Fail2ban limits tightened
#
# After this module runs:
#   - SSH over public IP: CLOSED
#   - SSH over VPN (10.100.0.1): OPEN
#   - Login as root: DENIED
#   - Login as admin: ALLOWED (with sudo -i)
#
# WARNING: Ensure VPN is working before running this module!
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "${SCRIPT_DIR}/lib/logging.sh"
source "${SCRIPT_DIR}/lib/backup.sh"

BOOTSTRAP_MODULE="harden"

# Load environment
if [[ -f "${SCRIPT_DIR}/.env" ]]; then
  # shellcheck source=/dev/null
  source "${SCRIPT_DIR}/.env"
fi

ADMIN_USER="${ADMIN_USER:-admin}"
SSH_ALLOW_USERS="${ADMIN_USER}"

# ── Build SSH allow-list (admin + vpn-cli additional users) ───────────────
build_ssh_allow_users() {
  local allow_users="${ADMIN_USER}"
  local users_json="${ADDITIONAL_USERS:-[]}"

  if ! command -v jq &>/dev/null; then
    log_warn "jq not installed - SSH AllowUsers will include only admin user"
    SSH_ALLOW_USERS="${allow_users}"
    return 0
  fi

  if [[ -n "$users_json" ]] && [[ "$users_json" != "[]" ]]; then
    local cli_users
    cli_users="$(echo "$users_json" | jq -r '.[] | select((.groups // []) | index("vpn-cli")) | .username' 2>/dev/null || true)"

    if [[ -n "$cli_users" ]]; then
      while IFS= read -r username; do
        [[ -z "$username" ]] && continue
        [[ "$username" == "$ADMIN_USER" ]] && continue
        allow_users+=" ${username}"
      done <<< "$cli_users"
    fi
  fi

  SSH_ALLOW_USERS="$allow_users"
  log_info "SSH AllowUsers resolved to: ${SSH_ALLOW_USERS}"
}

# ── Verify prerequisites ────────────────────────────────────────────────────
verify_prerequisites() {
  log_step "Verifying prerequisites for hardening"
  
  # Check admin user exists
  if ! id "$ADMIN_USER" &>/dev/null; then
    log_fatal "Admin user '$ADMIN_USER' does not exist. Run 01-system.sh first."
  fi
  log_info "Admin user '$ADMIN_USER' exists"
  
  # Check WireGuard is up
  if ! ip link show wg0 &>/dev/null; then
    log_fatal "WireGuard interface wg0 not found. Run 02-wireguard.sh first."
  fi
  log_info "WireGuard interface wg0 is up"
  
  # Check admin has SSH key
  local admin_home
  admin_home="$(getent passwd "$ADMIN_USER" | cut -d: -f6)"
  if [[ ! -f "${admin_home}/.ssh/authorized_keys" ]]; then
    log_fatal "No SSH keys for '$ADMIN_USER'. Cannot proceed with lockdown."
  fi
  log_info "Admin user has SSH authorized_keys"
}

# ── Configure SSH to only listen on VPN ─────────────────────────────────────
harden_ssh() {
  log_step "Configuring SSH for VPN-only access"
  
  local config_file="/etc/ssh/sshd_config.d/99-hardened.conf"
  
  local content
  content="$(cat <<EOF
# =============================================================================
# SSH Hardened Configuration
# Generated by vps-bootstrap 06-harden.sh
# =============================================================================

# ── NETWORK: Only listen on VPN interface ───────────────────────────────────
# After this, SSH is NOT accessible over the public IP!
ListenAddress 10.100.0.1
Port 22

# ── AUTHENTICATION: Keys only, no root ──────────────────────────────────────
PermitRootLogin no
PasswordAuthentication no
PubkeyAuthentication yes
AuthenticationMethods publickey

# ── ACCESS CONTROL: Admin + vpn-cli users ───────────────────────────────────
AllowUsers ${SSH_ALLOW_USERS}

# ── SECURITY: Minimize attack surface ───────────────────────────────────────
X11Forwarding no
AllowTcpForwarding no
AllowAgentForwarding no
PermitTunnel no
PermitUserEnvironment no

# ── SESSION: Idle timeout (30 minutes) ──────────────────────────────────────
ClientAliveInterval 300
ClientAliveCountMax 6

# ── BRUTE-FORCE: Limit attempts ─────────────────────────────────────────────
MaxAuthTries 3
MaxSessions 5
LoginGraceTime 30
EOF
)"

  if file_matches "$config_file" "$content"; then
    log_info "SSH config already hardened"
    return 0
  fi

  if [[ "$DRY_RUN" == "true" ]]; then
    log_info "Would install hardened SSH config"
    return 0
  fi

  # Backup existing config
  backup_file "$config_file"
  
  install_content "$content" "$config_file" "0644"
  
  # Validate SSH config before restarting
  if ! sshd -t; then
    log_fatal "SSH config validation failed! Restoring backup..."
  fi
  
  log_info "SSH hardening applied (will take effect on restart)"
}

# ── Configure passwordless sudo for admin ───────────────────────────────────
configure_sudo() {
  log_step "Configuring passwordless sudo for $ADMIN_USER"
  
  local sudoers_file="/etc/sudoers.d/99-admin-nopasswd"
  local content="${ADMIN_USER} ALL=(ALL) NOPASSWD: ALL"
  
  if [[ -f "$sudoers_file" ]] && grep -qF "$content" "$sudoers_file"; then
    log_info "Sudoers already configured"
    return 0
  fi
  
  if [[ "$DRY_RUN" == "true" ]]; then
    log_info "Would configure passwordless sudo"
    return 0
  fi
  
  echo "$content" > "$sudoers_file"
  chmod 0440 "$sudoers_file"
  
  # Validate sudoers
  if ! visudo -cf "$sudoers_file"; then
    rm -f "$sudoers_file"
    log_fatal "Sudoers validation failed!"
  fi
  
  log_info "Passwordless sudo configured for $ADMIN_USER"
}

# ── Tighten Fail2ban limits ─────────────────────────────────────────────────
harden_fail2ban() {
  log_step "Tightening Fail2ban configuration"
  
  # Check if fail2ban is installed
  if ! command -v fail2ban-client &>/dev/null; then
    log_warn "Fail2ban not installed, skipping"
    return 0
  fi
  
  # Remove bootstrap-mode config (lenient limits)
  rm -f /etc/fail2ban/jail.d/00-bootstrap.conf 2>/dev/null || true
  
  # Ensure jail.d directory exists
  mkdir -p /etc/fail2ban/jail.d
  
  local config_file="/etc/fail2ban/jail.d/sshd.conf"
  local content
  content="$(cat <<EOF
# =============================================================================
# Fail2ban SSH jail - Production configuration
# Generated by vps-bootstrap 06-harden.sh
# =============================================================================
[sshd]
enabled = true
port = ssh
filter = sshd
logpath = /var/log/auth.log

# Strict limits: 3 attempts in 10 minutes = 24 hour ban
maxretry = 3
findtime = 600
bantime = 86400
EOF
)"

  if [[ "$DRY_RUN" == "true" ]]; then
    log_info "Would install strict Fail2ban config"
    return 0
  fi
  
  echo "$content" > "$config_file"
  chmod 0644 "$config_file"
  
  systemctl reload fail2ban || true
  log_info "Fail2ban limits tightened (3 attempts = 24h ban)"
}

# ── Disable root account ────────────────────────────────────────────────────
disable_root() {
  log_step "Disabling root account"
  
  if [[ "$DRY_RUN" == "true" ]]; then
    log_info "Would lock root account"
    return 0
  fi
  
  # Lock root password (prevents password login)
  passwd -l root
  
  # Root can still be accessed via "sudo -i" from admin user
  log_info "Root account locked (use sudo -i from $ADMIN_USER)"
}

# ── Restart SSH service ─────────────────────────────────────────────────────
restart_ssh() {
  log_step "Restarting SSH service"
  
  if [[ "$DRY_RUN" == "true" ]]; then
    log_info "Would restart SSH"
    return 0
  fi
  
  # Show warning before restart
  log_warn "╔════════════════════════════════════════════════════════════════╗"
  log_warn "║  SSH will now restart and only listen on 10.100.0.1 (VPN)     ║"
  log_warn "║  Make sure VPN is working before disconnecting!               ║"
  log_warn "╚════════════════════════════════════════════════════════════════╝"
  
  systemctl restart ssh
  
  log_info "SSH restarted - now only accessible via VPN"
}

# ── Main ────────────────────────────────────────────────────────────────────
main() {
  module_start "06-harden"
  require_root
  
  verify_prerequisites
  build_ssh_allow_users
  harden_ssh
  configure_sudo
  harden_fail2ban
  disable_root
  restart_ssh
  
  log_warn "════════════════════════════════════════════════════════════════"
  log_warn "  HARDENING COMPLETE!"
  log_warn "  SSH is now VPN-only (10.100.0.1:22)"
  log_warn "  Login: ssh ${ADMIN_USER}@10.100.0.1"
  log_warn "  Root:  sudo -i"
  log_warn "════════════════════════════════════════════════════════════════"
  
  module_done
}

main "$@"
