#!/usr/bin/env bash
# =============================================================================
# services/n8n.sh — n8n + PostgreSQL (VPN-only via Traefik)
# =============================================================================
# Optional module.
#
# Deploys:
#   - PostgreSQL 16 (Alpine) at 10.20.0.41
#   - n8n (latest) at 10.20.0.40
#
# Access model:
#   VPN → Traefik:443 → n8n.<domain> → n8n:5678 (HTTP)
#
# Security design:
#   - NO published ports (no `ports:` directive)
#   - Traffic must go through Traefik + vpn-only middleware (ipAllowList)
#   - n8n protected with Basic Auth
#   - Secrets via environment variables (sourced from bootstrap/.env)
#   - Containers with no-new-privileges + capability drop
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "${SCRIPT_DIR}/lib/logging.sh"
source "${SCRIPT_DIR}/lib/backup.sh"

BOOTSTRAP_MODULE="n8n"

# Load environment
if [[ -f "${SCRIPT_DIR}/.env" ]]; then
  # shellcheck source=/dev/null
  source "${SCRIPT_DIR}/.env"
fi

VPN_DOMAIN="${VPN_DOMAIN:-example.com}"

# n8n secrets (generated by apply.sh unless set)
N8N_DB_PASSWORD="${N8N_DB_PASSWORD:-__N8N_DB_PASSWORD__}"
N8N_ENCRYPTION_KEY="${N8N_ENCRYPTION_KEY:-__N8N_ENCRYPTION_KEY__}"
N8N_ADMIN_EMAIL="${N8N_ADMIN_EMAIL:-admin@example.com}"
N8N_ADMIN_PASSWORD="${N8N_ADMIN_PASSWORD:-__N8N_ADMIN_PASSWORD__}"

# Optional: OpenAI key for workflows that call OpenAI directly
OPENAI_API_KEY="${OPENAI_API_KEY:-__OPENAI_API_KEY__}"

N8N_DIR="/opt/n8n"
TRAEFIK_DYNAMIC="/opt/traefik/dynamic.yml"
TRAEFIK_ACME_STATE_FILE="/opt/traefik/.acme-active"

traefik_https_tls_block() {
  if [[ -f "$TRAEFIK_ACME_STATE_FILE" ]] && grep -qx 'true' "$TRAEFIK_ACME_STATE_FILE"; then
    cat <<'YAML'
      tls:
        certResolver: le
YAML
  else
    echo '      tls: {}'
  fi
}

# ── Create directory structure ───────────────────────────────────────────────
setup_directories() {
  log_step "Creating n8n directory structure"

  if [[ "$DRY_RUN" == "true" ]]; then
    log_info "Would create $N8N_DIR"
    return 0
  fi

  mkdir -p "${N8N_DIR}/n8n-data"
  mkdir -p "${N8N_DIR}/pg-data"

  # n8n runs as node user (UID 1000) in the official image
  chown -R 1000:1000 "${N8N_DIR}/n8n-data"

  log_info "Created $N8N_DIR"
}

# ── Generate docker-compose.yml ──────────────────────────────────────────────
install_compose_file() {
  log_step "Installing n8n docker-compose.yml"

  local compose_file="${N8N_DIR}/docker-compose.yml"

  local content
  content="$(cat <<'YAML'
# =============================================================================
# docker-compose.yml — n8n + PostgreSQL
# =============================================================================
# NO ports: directive — accessible only via Traefik (10.20.0.10).

services:
  postgres:
    image: postgres:16-alpine
    container_name: n8n-postgres
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 3s
      retries: 10
    networks:
      vpn_net:
        ipv4_address: 10.20.0.41

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    env_file: .env
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=10.20.0.41
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - DB_POSTGRESDB_USER=${POSTGRES_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
      # n8n security & owner user setup
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      # Create owner user on first startup if no users exist
      - N8N_DEFAULT_USER_EMAIL=${N8N_ADMIN_EMAIL}
      - N8N_DEFAULT_USER_PASSWORD=${N8N_ADMIN_PASSWORD}
      # URL / Webhooks (Traefik terminates TLS)
      - N8N_HOST=n8n.${VPN_DOMAIN}
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://n8n.${VPN_DOMAIN}/
      # Timezone
      - GENERIC_TIMEZONE=Europe/Zurich
      - TZ=Europe/Zurich
      # Optional: OpenAI key for workflows
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    security_opt:
      - no-new-privileges:true
    cap_drop: ["ALL"]
    volumes:
      - ./n8n-data:/home/node/.n8n
    networks:
      vpn_net:
        ipv4_address: 10.20.0.40

networks:
  vpn_net:
    external: true
YAML
)"

  if file_matches "$compose_file" "$content"; then
    log_info "docker-compose.yml already up to date"
    return 0
  fi

  install_content "$content" "$compose_file" "0644"
}

# ── Generate .env file ──────────────────────────────────────────────────────
install_env_file() {
  log_step "Installing n8n .env file"

  local env_file="${N8N_DIR}/.env"

  if [[ "$N8N_DB_PASSWORD" == "__N8N_DB_PASSWORD__" ]]; then
    log_warn "N8N_DB_PASSWORD not set — using placeholder"
  fi
  if [[ "$N8N_ENCRYPTION_KEY" == "__N8N_ENCRYPTION_KEY__" ]]; then
    log_warn "N8N_ENCRYPTION_KEY not set — using placeholder"
  fi
  if [[ "$N8N_ADMIN_PASSWORD" == "__N8N_ADMIN_PASSWORD__" ]]; then
    log_warn "N8N_ADMIN_PASSWORD not set — using placeholder"
  fi
  if [[ "$N8N_ADMIN_EMAIL" == "admin@example.com" ]]; then
    log_warn "N8N_ADMIN_EMAIL not set — using default admin@example.com"
  fi
  if [[ "$OPENAI_API_KEY" == "__OPENAI_API_KEY__" ]]; then
    log_warn "OPENAI_API_KEY not set — n8n AI workflows using OpenAI will fail until you set it"
  fi

  local content
  content="$(cat <<EOF
# Domain
VPN_DOMAIN=${VPN_DOMAIN}

# PostgreSQL
POSTGRES_DB=n8n
POSTGRES_USER=n8n
POSTGRES_PASSWORD=${N8N_DB_PASSWORD}

# n8n
N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
N8N_ADMIN_EMAIL=${N8N_ADMIN_EMAIL}
N8N_ADMIN_PASSWORD=${N8N_ADMIN_PASSWORD}

# Optional: OpenAI
OPENAI_API_KEY=${OPENAI_API_KEY}
EOF
)"

  if file_matches "$env_file" "$content"; then
    log_info ".env already up to date"
    return 0
  fi

  install_content "$content" "$env_file" "0600"
}

# ── Patch Traefik dynamic.yml ───────────────────────────────────────────────
patch_traefik_routes() {
  log_step "Ensuring Traefik route exists for n8n.${VPN_DOMAIN}"

  if [[ "$DRY_RUN" == "true" ]]; then
    log_info "Would patch ${TRAEFIK_DYNAMIC}"
    return 0
  fi

  if [[ ! -f "$TRAEFIK_DYNAMIC" ]]; then
    log_fatal "Traefik dynamic config not found at ${TRAEFIK_DYNAMIC}. Run core/05-traefik first."
  fi

  # Idempotency: do nothing if router already exists
  if grep -qE '^\s*n8n:\s*$' "$TRAEFIK_DYNAMIC"; then
    log_info "Traefik router 'n8n' already present"
    return 0
  fi

  # Patch file content deterministically (Traefik uses file provider).
  # We insert:
  #   - router `n8n` under http.routers
  #   - service `n8n-svc` under http.services
  # right next to the existing git-web entries.

  # IMPORTANT: This heredoc is single-quoted so bash does NOT interpret backticks
  # in the Traefik Host(`...`) rule.
  local tls_block
  tls_block="$(traefik_https_tls_block)"

  VPN_DOMAIN="$VPN_DOMAIN" TRAEFIK_DYNAMIC="$TRAEFIK_DYNAMIC" TLS_BLOCK="$tls_block" python3 - <<'PY'
from pathlib import Path
import os

vpn_domain = os.environ["VPN_DOMAIN"]
path = os.environ["TRAEFIK_DYNAMIC"]
tls_block = os.environ["TLS_BLOCK"]
p = Path(path)
text = p.read_text(encoding="utf-8")

router_snip = f"""

    # n8n web UI
    n8n:
      entryPoints: [\"websecure\"]
      rule: \"Host(`n8n.{vpn_domain}`)\"
      middlewares: [\"vpn-only\"]
      service: n8n-svc
{tls_block}
"""

service_snip = """

    n8n-svc:
      loadBalancer:
        servers:
          - url: \"http://10.20.0.40:5678\"
"""

if "\n    n8n:\n" in text or "\n    n8n-svc:\n" in text:
    # Already patched (or partially patched). Keep idempotent.
    p.write_text(text, encoding="utf-8")
    raise SystemExit(0)

needle_services = "\n  services:\n"
if needle_services not in text:
    raise SystemExit("Could not find 'http.services' section in Traefik dynamic.yml")

text = text.replace(needle_services, router_snip + needle_services, 1)

needle_tcp = "\n# ── TCP routers"
if needle_tcp not in text:
    needle_tcp = "\ntcp:\n"
    if needle_tcp not in text:
        raise SystemExit("Could not find tcp section in Traefik dynamic.yml")
    text = text.replace(needle_tcp, service_snip + needle_tcp, 1)
else:
    text = text.replace(needle_tcp, service_snip + needle_tcp, 1)

p.write_text(text, encoding="utf-8")
PY

  chmod 0644 "$TRAEFIK_DYNAMIC"

  log_info "✅ Added Traefik router+service for n8n.${VPN_DOMAIN}"
  
  # Reload Traefik to pick up new routes (bind-mount doesn't always trigger inotify)
  if docker ps --filter "name=^/traefik$" --format '{{.Names}}' | grep -q '^traefik$'; then
    log_info "Restarting Traefik to apply new routes..."
    (cd /opt/traefik && docker compose restart traefik) || log_warn "Failed to restart Traefik"
  fi
}

# ── Deploy n8n stack ────────────────────────────────────────────────────────
deploy_n8n() {
  log_step "Deploying n8n stack"

  if [[ "$DRY_RUN" == "true" ]]; then
    log_info "Would deploy n8n via docker compose"
    return 0
  fi

  cd "${N8N_DIR}"

  # NOTE: Avoid a separate `docker compose pull`, which can hang indefinitely
  # in non-interactive Terraform remote-exec sessions. `up -d` pulls missing
  # images automatically.
  docker compose up -d --remove-orphans

  # Wait for postgres health
  log_info "Waiting for n8n PostgreSQL health check..."
  local i=0
  while [[ $i -lt 60 ]]; do
    if docker inspect --format='{{.State.Health.Status}}' n8n-postgres 2>/dev/null | grep -q healthy; then
      log_info "n8n PostgreSQL is healthy"
      break
    fi
    sleep 2
    i=$((i + 2))
  done

  # Wait for n8n container
  i=0
  while [[ $i -lt 30 ]]; do
    if docker ps --filter "name=^/n8n$" --filter "status=running" --format '{{.Names}}' | grep -q '^n8n$'; then
      log_info "n8n container is running"
      return 0
    fi
    sleep 1
    i=$((i + 1))
  done

  log_warn "n8n may not be fully started yet"
}

# ── Main ─────────────────────────────────────────────────────────────────────
main() {
  module_start "$BOOTSTRAP_MODULE"
  require_root

  setup_directories
  install_compose_file
  install_env_file
  patch_traefik_routes
  deploy_n8n

  module_done
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
  main "$@"
fi
