#!/usr/bin/env bash
# =============================================================================
# services/pihole.sh — Pi-hole DNS Ad Blocker (VPN-only via Traefik + Direct DNS)
# =============================================================================
# Deploys:
#   - Pi-hole at 10.20.0.71
#
# Architecture:
#   VPN → Traefik:443 → dns.<domain> → Pi-hole:80 (Web Admin)
#   VPN → 10.20.0.71:53 → Pi-hole DNS (Direct)
#
# Security design:
#   - NO published ports (no `ports:` directive)
#   - Web admin via Traefik + vpn-only middleware (ipAllowList)
#   - DNS accessible from VPN clients via firewall rule
#   - Containers with no-new-privileges + minimal capabilities
#
# VPN Client DNS Configuration:
#   To use Pi-hole for ad blocking, configure VPN clients to use
#   DNS = 10.20.0.71 in their WireGuard config.
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "${SCRIPT_DIR}/lib/logging.sh"
source "${SCRIPT_DIR}/lib/backup.sh"

BOOTSTRAP_MODULE="pihole"

# Load environment
if [[ -f "${SCRIPT_DIR}/.env" ]]; then
  # shellcheck source=/dev/null
  source "${SCRIPT_DIR}/.env"
fi

VPN_DOMAIN="${VPN_DOMAIN:-example.com}"
PIHOLE_ADMIN_PASSWORD="${PIHOLE_ADMIN_PASSWORD:-}"

PIHOLE_DIR="/opt/pihole"
TRAEFIK_DYNAMIC="/opt/traefik/dynamic.yml"
TRAEFIK_ACME_STATE_FILE="/opt/traefik/.acme-active"

traefik_https_tls_block() {
  if [[ -f "$TRAEFIK_ACME_STATE_FILE" ]] && grep -qx 'true' "$TRAEFIK_ACME_STATE_FILE"; then
    cat <<'YAML'
      tls:
        certResolver: le
YAML
  else
    echo '      tls: {}'
  fi
}

# ── Create directory structure ───────────────────────────────────────────────
setup_directories() {
  log_step "Creating Pi-hole directory structure"

  if [[ "$DRY_RUN" == "true" ]]; then
    log_info "Would create $PIHOLE_DIR"
    return 0
  fi

  mkdir -p "${PIHOLE_DIR}/etc-pihole"
  mkdir -p "${PIHOLE_DIR}/etc-dnsmasq.d"

  log_info "Created $PIHOLE_DIR"
}

# ── Generate .env file ─────────────────────────────────────────────────────
install_env_file() {
  log_step "Installing Pi-hole .env file"

  local env_file="${PIHOLE_DIR}/.env"

  # Pi-hole uses WEBPASSWORD environment variable
  local content
  content="$(cat <<EOF
# Pi-hole environment
# Generated by bootstrap - DO NOT EDIT MANUALLY

# Web admin password
WEBPASSWORD=${PIHOLE_ADMIN_PASSWORD}

# Timezone
TZ=Europe/Zurich

# DNS settings - use Cloudflare and Quad9 as upstream
PIHOLE_DNS_=1.1.1.1;9.9.9.9

# Don't use DHCP (we only want DNS)
DHCP_ACTIVE=false

# Web interface settings
VIRTUAL_HOST=dns.${VPN_DOMAIN}
WEB_PORT=80

# Query logging
QUERY_LOGGING=true
EOF
)"

  if file_matches "$env_file" "$content"; then
    log_info ".env already up to date"
    return 0
  fi

  install_content "$content" "$env_file" "0600"
}

# ── Generate docker-compose.yml ──────────────────────────────────────────────
install_compose_file() {
  log_step "Installing Pi-hole docker-compose.yml"

  local compose_file="${PIHOLE_DIR}/docker-compose.yml"

  local content
  content="$(cat <<'YAML'
# =============================================================================
# docker-compose.yml — Pi-hole DNS Ad Blocker
# =============================================================================
# NO ports: directive — Web UI accessible only via Traefik (10.20.0.10).
# DNS accessible from VPN clients via firewall rule.
#
# VPN clients should configure: DNS = 10.20.0.71

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    hostname: pihole
    restart: unless-stopped
    env_file: .env
    security_opt:
      - no-new-privileges:true
    cap_drop: ["ALL"]
    # Pi-hole needs these capabilities for DNS operations
    cap_add:
      - NET_BIND_SERVICE  # Bind to port 53
      - CHOWN
      - SETUID
      - SETGID
      - DAC_OVERRIDE
    volumes:
      - ./etc-pihole:/etc/pihole
      - ./etc-dnsmasq.d:/etc/dnsmasq.d
    dns:
      - 127.0.0.1
      - 1.1.1.1
    healthcheck:
      test: ["CMD-SHELL", "dig +short +norecurse +retry=0 @127.0.0.1 pi.hole || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      vpn_net:
        ipv4_address: 10.20.0.71

networks:
  vpn_net:
    external: true
YAML
)"

  if file_matches "$compose_file" "$content"; then
    log_info "docker-compose.yml already up to date"
    return 0
  fi

  install_content "$content" "$compose_file" "0644"
}

# ── Patch Traefik dynamic.yml ───────────────────────────────────────────────
patch_traefik_routes() {
  log_step "Ensuring Traefik route exists for dns.${VPN_DOMAIN}"

  if [[ "$DRY_RUN" == "true" ]]; then
    log_info "Would patch ${TRAEFIK_DYNAMIC}"
    return 0
  fi

  if [[ ! -f "$TRAEFIK_DYNAMIC" ]]; then
    log_fatal "Traefik dynamic config not found at ${TRAEFIK_DYNAMIC}. Run core/05-traefik first."
  fi

  # Idempotency: do nothing if router already exists
  if grep -qE '^\s*pihole:\s*$' "$TRAEFIK_DYNAMIC"; then
    log_info "Traefik router 'pihole' already present"
    return 0
  fi

  local tls_block
  tls_block="$(traefik_https_tls_block)"

  VPN_DOMAIN="$VPN_DOMAIN" TRAEFIK_DYNAMIC="$TRAEFIK_DYNAMIC" TLS_BLOCK="$tls_block" python3 - <<'PY'
from pathlib import Path
import os

vpn_domain = os.environ["VPN_DOMAIN"]
path = os.environ["TRAEFIK_DYNAMIC"]
tls_block = os.environ["TLS_BLOCK"]
p = Path(path)
text = p.read_text(encoding="utf-8")

router_snip = f"""

    # Pi-hole DNS admin
    pihole:
      entryPoints: ["websecure"]
      rule: "Host(`dns.{vpn_domain}`)"
      middlewares: ["vpn-only"]
      service: pihole-svc
{tls_block}
"""

service_snip = """

    pihole-svc:
      loadBalancer:
        servers:
          - url: "http://10.20.0.71:80"
"""

if "\n    pihole:\n" in text or "\n    pihole-svc:\n" in text:
    # Already patched (or partially patched). Keep idempotent.
    p.write_text(text, encoding="utf-8")
    raise SystemExit(0)

needle_services = "\n  services:\n"
if needle_services not in text:
    raise SystemExit("Could not find 'http.services' section in Traefik dynamic.yml")

text = text.replace(needle_services, router_snip + needle_services, 1)

needle_tcp = "\n# ── TCP routers"
if needle_tcp not in text:
    needle_tcp = "\ntcp:\n"
    if needle_tcp not in text:
        raise SystemExit("Could not find tcp section in Traefik dynamic.yml")
    text = text.replace(needle_tcp, service_snip + needle_tcp, 1)
else:
    text = text.replace(needle_tcp, service_snip + needle_tcp, 1)

p.write_text(text, encoding="utf-8")
PY

  chmod 0644 "$TRAEFIK_DYNAMIC"

  log_info "✅ Added Traefik router+service for dns.${VPN_DOMAIN}"

  # Reload Traefik to pick up new routes (bind-mount doesn't always trigger inotify)
  if docker ps --filter "name=^/traefik$" --format '{{.Names}}' | grep -q '^traefik$'; then
    log_info "Restarting Traefik to apply new routes..."
    (cd /opt/traefik && docker compose restart traefik) || log_warn "Failed to restart Traefik"
  fi
}

# ── Deploy pihole stack ──────────────────────────────────────────────────────
deploy_pihole() {
  log_step "Deploying Pi-hole stack"

  if [[ "$DRY_RUN" == "true" ]]; then
    log_info "Would deploy pihole via docker compose"
    return 0
  fi

  cd "${PIHOLE_DIR}"

  # NOTE: Avoid a separate `docker compose pull`, which can hang indefinitely
  # in non-interactive Terraform remote-exec sessions. `up -d` pulls missing
  # images automatically.
  docker compose up -d --remove-orphans

  # Wait for pihole container and health check
  log_info "Waiting for Pi-hole to start..."
  local i=0
  while [[ $i -lt 90 ]]; do
    if docker ps --filter "name=^/pihole$" --filter "status=running" --format '{{.Names}}' | grep -q '^pihole$'; then
      # Check health status
      local health
      health=$(docker inspect --format='{{.State.Health.Status}}' pihole 2>/dev/null || echo "unknown")
      if [[ "$health" == "healthy" ]]; then
        log_info "Pi-hole is healthy"
        return 0
      fi
    fi
    sleep 2
    i=$((i + 2))
  done

  if docker ps --filter "name=^/pihole$" --filter "status=running" --format '{{.Names}}' | grep -q '^pihole$'; then
    log_info "Pi-hole container is running (health check pending)"
    return 0
  fi

  log_warn "Pi-hole may not be fully started yet"
}

# ── Update gravity database ──────────────────────────────────────────────────
update_gravity() {
  log_step "Updating Pi-hole gravity database (ad lists)"

  if [[ "$DRY_RUN" == "true" ]]; then
    log_info "Would update Pi-hole gravity"
    return 0
  fi

  # Wait for Pi-hole to be ready
  local i=0
  while [[ $i -lt 30 ]]; do
    if docker exec pihole pihole status &>/dev/null; then
      break
    fi
    sleep 2
    i=$((i + 2))
  done

  # Update gravity in background (it takes a while)
  log_info "Running gravity update (downloading ad lists)..."
  if docker exec pihole pihole -g &>/dev/null; then
    log_info "Gravity update complete"
  else
    log_warn "Gravity update may still be in progress"
  fi
}

# ── Print post-deploy instructions ──────────────────────────────────────────
print_instructions() {
  log_step "Pi-hole deployment complete"

  echo "" >&2
  log_info "════════════════════════════════════════════════════════════════"
  log_info "  Pi-hole DNS Ad Blocker"
  log_info "════════════════════════════════════════════════════════════════"
  log_info "  Web Admin:  https://dns.${VPN_DOMAIN}/admin"
  log_info "  Password:   (see terraform output -json credentials | jq '.pihole')"
  log_info "  DNS IP:     10.20.0.71"
  log_info "  Data:       ${PIHOLE_DIR}/etc-pihole/"
  log_info ""
  log_info "  To use Pi-hole, configure your VPN clients:"
  log_info "    DNS = 10.20.0.71"
  log_info "════════════════════════════════════════════════════════════════"
  echo "" >&2
}

# ── Main ─────────────────────────────────────────────────────────────────────
main() {
  module_start "$BOOTSTRAP_MODULE"
  require_root

  setup_directories
  install_env_file
  install_compose_file
  patch_traefik_routes
  deploy_pihole
  update_gravity
  print_instructions

  module_done
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
  main "$@"
fi
